# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-02 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_convert_snapshot_to_dict'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('-pk',), 'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
    ]
