# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-02 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationsupplement',
            name='registration_profile',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='_registrations_registrationsupplement_supplement', to='registration.RegistrationProfile', verbose_name='registration profile'),
        ),
    ]
